name: first
on: push
jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
    packages:
        needs: code
        runs-on: ubuntu-latest
        steps:
            - name: Install Dependencies
              run: npm install
    lint:
        needs: packages
        runs-on: ubuntu-latest
        steps:
            - name : Run Lint
              run: npm lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        name: Run Tests
        steps:
            - run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Application
              run: echo "Deploying application"
