name: first
on: push
jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'
            - run: npm install
    lint:
        needs: code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'
            - name : Run Lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        name: Run Tests
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                cache: 'npm'
            - run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Application
              run: echo "Deploying application"
